### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by ttguy** [ma99us/VPNKillSwitch#1]
So this is a common issue with Java and I forget how I solved it last time. 
Any hints on how to prevent this ?
~/development/VPNKillSwitch-master$ java VPNKillSwitch.jar
Error: Could not find or load main class VPNKillSwitch.jar
Caused by: java.lang.ClassNotFoundException: VPNKillSwitch.jar

java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3, mixed mode)

**Comment by ma99us** [comment]
Hi,
try this command:
~/ java *-jar* VPNKillSwitch.jar

M.

**Comment by ttguy** [comment]
Thanks dude 
This worked:

cd ~/development/VPNKillSwitch-master
java -jar VPNKillSwitch.jar

**Comment by ttguy** [comment]
You could add that hint to your readme - to help out neophytes like me.!
